package lightfish.byteLexer;
 class CParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'l' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.CLEAR;return x;}}endId();return x;}}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.CLASS_ORIGIN;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='i'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CLIENT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CLOSE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'i' :{{c=cc(x);if(c=='p'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.CIPHER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'h' :{{c=cc(x);if(c=='a'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='l'){c=cc(x);if (isBlank(c)){t=H.CHANNEL;return x;}}endId();return x;}}endId();return x;}}if(c=='g'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.CHANGED;return x;}}return x;}}endId();return x;}}endId();return x;}}if(c=='r'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.CHARACTER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CHARSET;return x;}}endId();return x;}}endId();return x;}}return x;}}if(c=='i'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.CHAIN;return x;}}endId();return x;}}endId();return x;}}if(c=='e'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='k'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='m'){c=cc(x);if (isBlank(c)){t=H.CHECKSUM;return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'u' :{{c=cc(x);if(c=='b'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CUBE;return x;}}endId();return x;}}if(c=='r'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CURDATE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CURTIME;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CURSOR_NAME;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.CURRENT_USER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='d'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CURRENT_DATE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='p'){c=cc(x);if (isBlank(c)){t=H.CURRENT_TIMESTAMP;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'r' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CREATE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.CROSS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'a' :{{c=cc(x);if(c=='l'){{c=cc(x);if(c=='l'){c=cc(x);if (isBlank(c)){t=H.CALL;return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CATALOG_NAME;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CATLET;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='c'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CACHE;return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CASE;return x;}}if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CAST;return x;}}if(c=='c'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.CASCADED;return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'p' :{{c=cc(x);if(c=='u'){c=cc(x);if (isBlank(c)){t=H.CPU;return x;}}endId();return x;}}
case 'o' :{switch (cc(x)){
case 'n' :{switch (cc(x)){
case 'n' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.CONNECTION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'f' :{{c=cc(x);if(c=='i'){{c=cc(x);if(c=='g'){c=cc(x);if (isBlank(c)){t=H.CONFIG;return x;}}endId();return x;}}endId();return x;}}
case 'v' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CONVERT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'd' :{{c=cc(x);if(c=='i'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.CONDITION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 't' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='x'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CONTEXT;return x;}}endId();return x;}}endId();return x;}}if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='b'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.CONTRIBUTORS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.CONTAINS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CONTINUE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'c' :{{c=cc(x);if(c=='u'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CONCURRENT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 's' :{{c=cc(x);if(c=='i'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.CONSISTENT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CONSTRAINT_NAME;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='c'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='g'){c=cc(x);if (isBlank(c)){t=H.CONSTRAINT_CATALOG;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='a'){c=cc(x);if (isBlank(c)){t=H.CONSTRAINT_SCHEMA;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}
case 'm' :{{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.COMMENT;return x;}}endId();return x;}}endId();return x;}}if(c=='i'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.COMMITTED;return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}if(c=='p'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.COMPRESSED;return x;}}endId();return x;}}if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.COMPRESSION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.COMPACT;return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.COMPLETION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'u' :{{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.COUNT;return x;}}endId();return x;}}endId();return x;}}
case 'd' :{{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.CODE;return x;}}endId();return x;}}
case 'l' :{{c=cc(x);if(c=='u'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.COLUMN_FORMAT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.COLUMN_NAME;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){c=cc(x);if (isBlank(c)){t=H.COLUMNS;return x;}}return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.COLLATE;return x;}}if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.COLLATION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'a' :{{c=cc(x);if(c=='l'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.COALESCE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}
default:endId();return x;
}}}