package lightfish.byteLexer;
class EParseNode extends P{public  int parse(){int c;switch (cc(x)){
case 'n' :{{return n();}}
case 'l' :{{return l();}}
case 'x' :{{return x();}}
case 'v' :{{return v();}}
case 's' :{{return s();}}
case 'r' :{{return r();}}
case 'a' :{{return a();}}
default:endId();return x;
}};private int a(){int c;if(x<size){c=cc(x);if(c=='c'){if(x<size){c=cc(x);if(c=='h'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EACH;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}private int l(){int c;if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='f'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ELSEIF;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}private int n(){int c;switch (cc(x)){
case 'u' :{if(x<size){c=cc(x);if(c=='m'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ENUM;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}
case 'd' :{if(x<size){c=cc(x);if(c=='_'){if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='f'){if(x<size){c=cc(x);if(c=='_'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='p'){if(x<size){c=cc(x);if(c=='u'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.END_OF_INPUT;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}if(c=='s'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ENDS;return x;}else{endId();return x;}}else{return x;}}return x;}return x;}
case 'c' :{if(x<size){c=cc(x);if(c=='l'){if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='d'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ENCLOSED;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'a' :{if(x<size){c=cc(x);if(c=='b'){if(x<size){c=cc(x);if(c=='l'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ENABLE;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'g' :{if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ENGINES;return x;}else{endId();return x;}}else{return x;}}return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
default:endId();return x;
}}private int r(){int c;if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ERRORS;return x;}else{endId();return x;}}else{return x;}}return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}private int s(){int c;if(x<size){c=cc(x);if(c=='c'){if(x<size){c=cc(x);if(c=='a'){if(x<size){c=cc(x);if(c=='p'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='d'){if(x<size){c=cc(x);if (isBlank(c)){t=H.ESCAPED;return x;}else{endId();return x;}}else{return x;}}return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}private int v(){int c;if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EVENTS;return x;}else{endId();return x;}}else{return x;}}return x;}return x;}endId();return x;}return x;}if(c=='r'){if(x<size){c=cc(x);if(c=='y'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EVERY;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}private int x(){int c;switch (cc(x)){
case 'e' :{if(x<size){c=cc(x);if(c=='c'){if(x<size){c=cc(x);if(c=='u'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXECUTE;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 't' :{if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if(c=='a'){if(x<size){c=cc(x);if(c=='c'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXTRACT;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}if(c=='e'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='d'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='d'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXTENDED;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}if(c=='t'){if(x<size){c=cc(x);if(c=='_'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='z'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXTENT_SIZE;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'c' :{if(x<size){c=cc(x);if(c=='h'){if(x<size){c=cc(x);if(c=='a'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='g'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXCHANGE;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'i' :{if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXIT;return x;}else{endId();return x;}}else{return x;}}if(c=='s'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXISTS;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'p' :{if(x<size){c=cc(x);if(c=='l'){if(x<size){c=cc(x);if(c=='a'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXPLAIN;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}if(c=='a'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXPANSION;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}if(c=='i'){if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXPIRE;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}if(c=='o'){if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.EXPORT;return x;}else{endId();return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
default:endId();return x;
}}}