package lightfish.byteLexer;
class EParseNode extends P{public  int parse(){int c;switch (c=cc()){
case 'n' :{{return n();}}
case 'l' :{{return l();}}
case 'x' :{{return x();}}
case 'v' :{{return v();}}
case 's' :{{return s();}}
case 'r' :{{return r();}}
case 'a' :{{return a();}}
default:endId(c);return x;
}};private int a(){int c;if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='h'){return endBlank(H.EACH);}endId(c);return x;}return x;}endId(c);return x;}return x;}private int l(){int c;if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='f'){return endBlank(H.ELSEIF);}endId(c);return x;}return x;}t=H.ELSE;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int n(){int c;switch (c=cc()){
case 'u' :{if(x<size){c=cc();if(c=='m'){return endBlank(H.ENUM);}endId(c);return x;}return x;}
case 'd' :{if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='p'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='t'){return endBlank(H.END_OF_INPUT);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='s'){return endBlank(H.ENDS);}t=H.END;return x;}return x;}
case 'c' :{if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.ENCLOSED);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'a' :{if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='e'){return endBlank(H.ENABLE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'g' :{if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='s'){return endBlank(H.ENGINES);}t=H.ENGINE;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
default:endId(c);return x;
}}private int r(){int c;if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='s'){return endBlank(H.ERRORS);}t=H.ERROR;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int s(){int c;if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='p'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.ESCAPED);}t=H.ESCAPE;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int v(){int c;if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='s'){return endBlank(H.EVENTS);}t=H.EVENT;return x;}return x;}endId(c);return x;}return x;}if(c=='r'){if(x<size){c=cc();if(c=='y'){return endBlank(H.EVERY);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int x(){int c;switch (c=cc()){
case 'e' :{if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){return endBlank(H.EXECUTE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 't' :{if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='t'){return endBlank(H.EXTRACT);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='e'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.EXTENDED);}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='t'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='z'){if(x<size){c=cc();if(c=='e'){return endBlank(H.EXTENT_SIZE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'c' :{if(x<size){c=cc();if(c=='h'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='g'){if(x<size){c=cc();if(c=='e'){return endBlank(H.EXCHANGE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'i' :{if(x<size){c=cc();if(c=='t'){return endBlank(H.EXIT);}if(c=='s'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='s'){return endBlank(H.EXISTS);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'p' :{if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){return endBlank(H.EXPLAIN);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='a'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='n'){return endBlank(H.EXPANSION);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='i'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='e'){return endBlank(H.EXPIRE);}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='o'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='t'){return endBlank(H.EXPORT);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
default:endId(c);return x;
}}}