package lightfish.byteLexer;
 class FParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'l' :{{c=cc(x);if(c=='u'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='h'){c=cc(x);if (isBlank(c)){t=H.FLUSH;return x;}}endId();return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='4'){c=cc(x);if (isBlank(c)){t=H.FLOAT4;return x;}}if(c=='8'){c=cc(x);if (isBlank(c)){t=H.FLOAT8;return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'i' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.FIELDS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='b'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='k'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='z'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.FILE_BLOCK_SIZE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.FILTER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='r'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.FIRST;return x;}}endId();return x;}}endId();return x;}}if(c=='x'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.FIXED;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'e' :{{c=cc(x);if(c=='t'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='h'){c=cc(x);if (isBlank(c)){t=H.FETCH;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'u' :{{c=cc(x);if(c=='n'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.FUNCTION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='x'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.FULLTEXT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}
case 'r' :{{c=cc(x);if(c=='a'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.FRAC_SECOND;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='m'){c=cc(x);if (isBlank(c)){t=H.FROM;return x;}}endId();return x;}}endId();return x;}}
case 'a' :{{c=cc(x);if(c=='u'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.FAULTS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.FALSE;return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.FAST;return x;}}endId();return x;}}endId();return x;}}
case 'o' :{{c=cc(x);if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.FOREIGN;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='m'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.FORMAT;return x;}}endId();return x;}}endId();return x;}}if(c=='c'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.FORCE;return x;}}endId();return x;}}return x;}}if(c=='u'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.FOUND;return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='w'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.FOLLOWS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}}