package lightfish.byteLexer;
 class IParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'n' :{switch (cc(x)){
case 'n' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.INNER;return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='b'){c=cc(x);if (isBlank(c)){t=H.INNODB;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'i' :{{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='z'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.INITIAL_SIZE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'f' :{{c=cc(x);if(c=='i'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.INFILE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'v' :{{c=cc(x);if(c=='o'){{c=cc(x);if(c=='k'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.INVOKER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'd' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='x'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.INDEXES;return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}
case 't' :{switch (cc(x)){
case '8' :{c=cc(x);if (isBlank(c)){t=H.INT8;return x;}}
case 'e' :{{c=cc(x);if(c=='r'){{c=cc(x);if(c=='v'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){c=cc(x);if (isBlank(c)){t=H.INTERVAL;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='g'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.INTEGER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case '4' :{c=cc(x);if (isBlank(c)){t=H.INT4;return x;}}
case '3' :{c=cc(x);if (isBlank(c)){t=H.INT3;return x;}}
case '2' :{c=cc(x);if (isBlank(c)){t=H.INT2;return x;}}
case '1' :{c=cc(x);if (isBlank(c)){t=H.INT1;return x;}}
case 'o' :{c=cc(x);if (isBlank(c)){t=H.INTO;return x;}}
default:endId();return x;
}}
case 's' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='v'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.INSENSITIVE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='r'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.INSERT_METHOD;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='l'){c=cc(x);if (isBlank(c)){t=H.INSTALL;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'o' :{{c=cc(x);if(c=='u'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.INOUT;return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}
case 'm' :{{c=cc(x);if(c=='p'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.IMPORT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'g' :{{c=cc(x);if(c=='n'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='v'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.IGNORE_SERVER_IDS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'f' :{c=cc(x);if (isBlank(c)){t=H.IF;return x;}}
case 'd' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.IDENTIFIED;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}
case 't' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.ITERATE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 's' :{{c=cc(x);if(c=='o'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.ISOLATION;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.ISSUER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}
case 'p' :{{c=cc(x);if(c=='c'){c=cc(x);if (isBlank(c)){t=H.IPC;return x;}}endId();return x;}}
case 'o' :{{c=cc(x);if(c=='_'){{c=cc(x);if(c=='b'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.IO_BEFORE_GTIDS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='d'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.IO_AFTER_GTIDS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.IO_THREAD;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}
default:endId();return x;
}}}