package lightfish.byteLexer;
class IParseNode extends P{public  int parse(){int c;switch (c=cc()){
case 'n' :{{return n();}}
case 'm' :{{return m();}}
case 'g' :{{return g();}}
case 'f' :{{return f();}}
case 'd' :{{return d();}}
case 't' :{{return t();}}
case 's' :{{return s();}}
case 'p' :{{return p();}}
case 'o' :{{return o();}}
default:endId(c);return x;
}};private int d(){int c;if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.IDENTIFIED);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.ID;return x;}return x;}private int f(){int c;return endBlank(H.IF);}private int g(){int c;if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='v'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='s'){return endBlank(H.IGNORE_SERVER_IDS);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.IGNORE;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int m(){int c;if(x<size){c=cc();if(c=='p'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='t'){return endBlank(H.IMPORT);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int n(){int c;switch (c=cc()){
case 'n' :{if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.INNER);}endId(c);return x;}return x;}if(c=='o'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='b'){return endBlank(H.INNODB);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'i' :{if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='z'){if(x<size){c=cc();if(c=='e'){return endBlank(H.INITIAL_SIZE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'f' :{if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='e'){return endBlank(H.INFILE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'v' :{if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='k'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.INVOKER);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'd' :{if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='x'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='s'){return endBlank(H.INDEXES);}endId(c);return x;}return x;}t=H.INDEX;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 't' :{switch (c=cc()){
case '8' :{return endBlank(H.INT8);}
case 'e' :{if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='v'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='l'){return endBlank(H.INTERVAL);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='g'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.INTEGER);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case '4' :{return endBlank(H.INT4);}
case '3' :{return endBlank(H.INT3);}
case '2' :{return endBlank(H.INT2);}
case '1' :{return endBlank(H.INT1);}
case 'o' :{return endBlank(H.INTO);}
default:if (isBlank(c)){t=H.INT;return x;}else{endId(c);return x;}
}}
case 's' :{if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='v'){if(x<size){c=cc();if(c=='e'){return endBlank(H.INSENSITIVE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='r'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='h'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='d'){return endBlank(H.INSERT_METHOD);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.INSERT;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='t'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='l'){return endBlank(H.INSTALL);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'o' :{if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='t'){return endBlank(H.INOUT);}endId(c);return x;}return x;}endId(c);return x;}return x;}
default:if (isBlank(c)){t=H.IN;return x;}else{endId(c);return x;}
}}private int o(){int c;if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='g'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='s'){return endBlank(H.IO_BEFORE_GTIDS);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='a'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='g'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='s'){return endBlank(H.IO_AFTER_GTIDS);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='t'){if(x<size){c=cc();if(c=='h'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='d'){return endBlank(H.IO_THREAD);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.IO;return x;}return x;}private int p(){int c;if(x<size){c=cc();if(c=='c'){return endBlank(H.IPC);}endId(c);return x;}return x;}private int s(){int c;if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='n'){return endBlank(H.ISOLATION);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='s'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.ISSUER);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.IS;return x;}return x;}private int t(){int c;if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){return endBlank(H.ITERATE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}}