package lightfish.byteLexer;
 class LParseNode extends P{  public  int parse(){int c;{c=cc(x);if(c=='e'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='t'){t=H.LEFT;++x;return x;}endId();return x;}}if(c=='v'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='l'){t=H.LEVEL;++x;return x;}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='s'){t=H.LESS;++x;return x;}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='v'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){t=H.LEAVES;++x;return x;}return x;}}endId();return x;}}if(c=='d'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='g'){t=H.LEADING;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='e'){t=H.LANGUAGE;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='t'){t=H.LAST;++x;return x;}endId();return x;}}endId();return x;}}if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='r'){t=H.LINEAR;++x;return x;}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='g'){t=H.LINESTRING;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}if(c=='m'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='t'){t=H.LIMIT;++x;return x;}endId();return x;}}endId();return x;}}if(c=='k'){{c=cc(x);if(c=='e'){t=H.LIKE;++x;return x;}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='t'){t=H.LIST;++x;return x;}endId();return x;}}endId();return x;}}if(c=='o'){switch (cc(x)){
case 'n' :{{c=cc(x);if(c=='g'){{c=cc(x);if(c=='b'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='b'){t=H.LONGBLOB;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='x'){{c=cc(x);if(c=='t'){t=H.LONGTEXT;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='_'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='m'){t=H.LONG_NUM;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}
case 'c' :{{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='p'){t=H.LOCALTIMESTAMP;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}if(c=='t'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){t=H.LOCATOR;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='k'){{c=cc(x);if(c=='s'){t=H.LOCKS;++x;return x;}return x;}}endId();return x;}}
case 'a' :{{c=cc(x);if(c=='d'){t=H.LOAD;++x;return x;}endId();return x;}}
case 'g' :{{c=cc(x);if(c=='f'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='e'){t=H.LOGFILE;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){t=H.LOGS;++x;return x;}endId();return x;}}
case 'o' :{{c=cc(x);if(c=='p'){t=H.LOOP;++x;return x;}endId();return x;}}
case 'w' :{{c=cc(x);if(c=='_'){{c=cc(x);if(c=='p'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='y'){t=H.LOW_PRIORITY;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}endId();return x;}}}