package lightfish.byteLexer;
class NParseNode extends P{public  int parse(){int c;switch (c=cc()){
case 'v' :{{return v();}}
case 'e' :{{return e();}}
case 'u' :{{return u();}}
case 'd' :{{return d();}}
case 'c' :{{return c();}}
case 'a' :{{return a();}}
case 'o' :{{return o();}}
default:endId(c);return x;
}};private int a(){int c;if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='s'){return endBlank(H.NAMES);}t=H.NAME;return x;}return x;}endId(c);return x;}return x;}if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='l'){return endBlank(H.NATIONAL);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='u'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='l'){return endBlank(H.NATURAL);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int c(){int c;if(x<size){c=cc();if(c=='h'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='g'){return endBlank(H.NCHAR_STRING);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.NCHAR;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int d(){int c;if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.NDBCLUSTER);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.NDB;return x;}return x;}endId(c);return x;}return x;}private int e(){int c;if(x<size){c=cc();if(c=='v'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.NEVER);}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='x'){if(x<size){c=cc();if(c=='t'){return endBlank(H.NEXT);}endId(c);return x;}return x;}if(c=='g'){return endBlank(H.NEG);}if(c=='w'){return endBlank(H.NEW);}endId(c);return x;}return x;}private int o(){int c;switch (c=cc()){
case 'n' :{if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='k'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='g'){return endBlank(H.NONBLOCKING);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='e'){return endBlank(H.NONE);}endId(c);return x;}return x;}
case 'd' :{if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='g'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='p'){return endBlank(H.NODEGROUP);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 't' :{return endBlank(H.NOT);}
case '_' :{if(x<size){c=cc();if(c=='w'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='g'){return endBlank(H.NO_WRITE_TO_BINLOG);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='a'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='t'){return endBlank(H.NO_WAIT);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'w' :{return endBlank(H.NOW);}
default:if (isBlank(c)){t=H.NO;return x;}else{endId(c);return x;}
}}private int u(){int c;if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){return endBlank(H.NUMBER);}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='c'){return endBlank(H.NUMERIC);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='l'){if(x<size){c=cc();if(c=='l'){return endBlank(H.NULL);}endId(c);return x;}return x;}endId(c);return x;}return x;}private int v(){int c;if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='h'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='r'){return endBlank(H.NVARCHAR);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}}