package lightfish.byteLexer;
 class NParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'v' :{{c=cc(x);if(c=='a'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='r'){t=H.NVARCHAR;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'e' :{{c=cc(x);if(c=='v'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){t=H.NEVER;++x;return x;}endId();return x;}}endId();return x;}}if(c=='x'){{c=cc(x);if(c=='t'){t=H.NEXT;++x;return x;}endId();return x;}}if(c=='g'){t=H.NEG;++x;return x;}if(c=='w'){t=H.NEW;++x;return x;}endId();return x;}}
case 'u' :{{c=cc(x);if(c=='m'){{c=cc(x);if(c=='b'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){t=H.NUMBER;++x;return x;}endId();return x;}}endId();return x;}}if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='c'){t=H.NUMERIC;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='l'){{c=cc(x);if(c=='l'){t=H.NULL;++x;return x;}endId();return x;}}endId();return x;}}
case 'd' :{{c=cc(x);if(c=='b'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){t=H.NDBCLUSTER;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}
case 'c' :{{c=cc(x);if(c=='h'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='g'){t=H.NCHAR_STRING;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'a' :{{c=cc(x);if(c=='m'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='s'){t=H.NAMES;++x;return x;}return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){t=H.NATIONAL;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='u'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){t=H.NATURAL;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'o' :{switch (cc(x)){
case 'n' :{{c=cc(x);if(c=='b'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='k'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='g'){t=H.NONBLOCKING;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='e'){t=H.NONE;++x;return x;}endId();return x;}}
case 'd' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='g'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='u'){{c=cc(x);if(c=='p'){t=H.NODEGROUP;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 't' :{t=H.NOT;++x;return x;}
case '_' :{{c=cc(x);if(c=='w'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='b'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='g'){t=H.NO_WRITE_TO_BINLOG;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='a'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='t'){t=H.NO_WAIT;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'w' :{t=H.NOW;++x;return x;}
default:endId();return x;
}}
default:endId();return x;
}}}