package lightfish.byteLexer;
 class OParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'n' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.ONE_SHOT;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}if(c=='l'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.ONLINE;return x;}}endId();return x;}}endId();return x;}}if(c=='y'){c=cc(x);if (isBlank(c)){t=H.ONLY;return x;}}endId();return x;}}return x;}}
case 'l' :{{c=cc(x);if(c=='d'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='p'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='w'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='d'){c=cc(x);if (isBlank(c)){t=H.OLD_PASSWORD;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'w' :{{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.OWNER;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'f' :{{c=cc(x);if(c=='f'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.OFFLINE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='t'){c=cc(x);if (isBlank(c)){t=H.OFFSET;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'u' :{{c=cc(x);if(c=='t'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='e'){c=cc(x);if (isBlank(c)){t=H.OUTFILE;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.OUTER;return x;}}endId();return x;}}return x;}}endId();return x;}}
case 'r' :{{c=cc(x);if(c=='d'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){c=cc(x);if (isBlank(c)){t=H.ORDER;return x;}}endId();return x;}}endId();return x;}}return x;}}
case 'p' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){c=cc(x);if (isBlank(c)){t=H.OPEN;return x;}}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='z'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='s'){c=cc(x);if (isBlank(c)){t=H.OPTIMIZER_COSTS;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='y'){c=cc(x);if (isBlank(c)){t=H.OPTIONALLY;return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){c=cc(x);if (isBlank(c)){t=H.OPTIONS;return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}}