package lightfish.byteLexer;
 class OParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'n' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='h'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='t'){t=H.ONE_SHOT;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}if(c=='l'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){t=H.ONLINE;++x;return x;}endId();return x;}}endId();return x;}}if(c=='y'){t=H.ONLY;++x;return x;}endId();return x;}}return x;}}
case 'l' :{{c=cc(x);if(c=='d'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='p'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='w'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='d'){t=H.OLD_PASSWORD;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'w' :{{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){t=H.OWNER;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}
case 'f' :{{c=cc(x);if(c=='f'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='e'){t=H.OFFLINE;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='t'){t=H.OFFSET;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
case 'u' :{{c=cc(x);if(c=='t'){{c=cc(x);if(c=='f'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='e'){t=H.OUTFILE;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='e'){{c=cc(x);if(c=='r'){t=H.OUTER;++x;return x;}endId();return x;}}return x;}}endId();return x;}}
case 'r' :{{c=cc(x);if(c=='d'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){t=H.ORDER;++x;return x;}endId();return x;}}endId();return x;}}return x;}}
case 'p' :{{c=cc(x);if(c=='e'){{c=cc(x);if(c=='n'){t=H.OPEN;++x;return x;}endId();return x;}}if(c=='t'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='m'){{c=cc(x);if(c=='i'){{c=cc(x);if(c=='z'){{c=cc(x);if(c=='e'){{c=cc(x);if(c=='r'){{c=cc(x);if(c=='_'){{c=cc(x);if(c=='c'){{c=cc(x);if(c=='o'){{c=cc(x);if(c=='s'){{c=cc(x);if(c=='t'){{c=cc(x);if(c=='s'){t=H.OPTIMIZER_COSTS;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='o'){{c=cc(x);if(c=='n'){{c=cc(x);if(c=='a'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='l'){{c=cc(x);if(c=='y'){t=H.OPTIONALLY;++x;return x;}endId();return x;}}endId();return x;}}endId();return x;}}if(c=='s'){t=H.OPTIONS;++x;return x;}return x;}}endId();return x;}}endId();return x;}}endId();return x;}}endId();return x;}}
default:endId();return x;
}}}