package lightfish.byteLexer;
 class SParseNode extends P{  public  int parse(){int c;switch (cc(x)){
case 'l' :{if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='w'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SLOW;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}
case 'h' :{if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='w'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SHOW;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}
case 'w' :{if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if(c=='c'){if(x<size){c=cc(x);if(c=='h'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SWITCH;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'e' :{if(x<size){c=cc(x);if(c=='l'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='c'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SELECT;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SET;return x;}}else{return x;}}if(c=='s'){if(x<size){c=cc(x);if(c=='s'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SESSION;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}if(c=='r'){if(x<size){c=cc(x);if(c=='v'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SERVER;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 't' :{if(x<size){c=cc(x);if(c=='a'){if(x<size){c=cc(x);if(c=='r'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if(c=='u'){if(x<size){c=cc(x);if(c=='p'){if(x<size){c=cc(x);if (isBlank(c)){t=H.STARTUP;return x;}}else{return x;}}endId();return x;}return x;}return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'c' :{if(x<size){c=cc(x);if(c=='h'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='m'){if(x<size){c=cc(x);if(c=='a'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SCHEMA;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'a' :{if(x<size){c=cc(x);if(c=='v'){if(x<size){c=cc(x);if(c=='e'){if(x<size){c=cc(x);if(c=='p'){if(x<size){c=cc(x);if(c=='o'){if(x<size){c=cc(x);if(c=='i'){if(x<size){c=cc(x);if(c=='n'){if(x<size){c=cc(x);if(c=='t'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SAVEPOINT;return x;}}else{return x;}}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}endId();return x;}return x;}
case 'q' :{if(x<size){c=cc(x);if(c=='l'){if(x<size){c=cc(x);if (isBlank(c)){t=H.SQL;return x;}}else{return x;}}endId();return x;}return x;}
default:endId();return x;
}}}