package lightfish.byteLexer;
class UParseNode extends P{public  int parse(){int c;switch (c=cc()){
case 'n' :{{return n();}}
case 'd' :{{return d();}}
case 't' :{{return t();}}
case 's' :{{return s();}}
case 'p' :{{return p();}}
default:endId(c);return x;
}};private int d(){int c;if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='s'){return endBlank(H.UDF_RETURNS);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int n(){int c;switch (c=cc()){
case 'l' :{if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='k'){return endBlank(H.UNLOCK);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'k' :{if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='w'){if(x<size){c=cc();if(c=='n'){return endBlank(H.UNKNOWN);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'i' :{if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='l'){return endBlank(H.UNINSTALL);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='c'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UNICODE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='q'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UNIQUE);}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='o'){if(x<size){c=cc();if(c=='n'){return endBlank(H.UNION);}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'd' :{if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.UNDEFINED);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='o'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='l'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UNDOFILE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='_'){if(x<size){c=cc();if(c=='b'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='z'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UNDO_BUFFER_SIZE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.UNDO;return x;}return x;}endId(c);return x;}return x;}
case 't' :{if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='l'){return endBlank(H.UNTIL);}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 'c' :{if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.UNCOMMITTED);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
case 's' :{if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='g'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='d'){return endBlank(H.UNSIGNED);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}
default:endId(c);return x;
}}private int p(){int c;if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UPDATE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='g'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UPGRADE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int s(){int c;if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='g'){if(x<size){c=cc();if(c=='e'){return endBlank(H.USAGE);}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='e'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='o'){if(x<size){c=cc();if(c=='u'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='s'){return endBlank(H.USER_RESOURCES);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.USER;return x;}return x;}if(c=='_'){if(x<size){c=cc();if(c=='f'){if(x<size){c=cc();if(c=='r'){if(x<size){c=cc();if(c=='m'){return endBlank(H.USE_FRM);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.USE;return x;}return x;}if(c=='i'){if(x<size){c=cc();if(c=='n'){if(x<size){c=cc();if(c=='g'){return endBlank(H.USING);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}private int t(){int c;if(x<size){c=cc();if(c=='c'){if(x<size){c=cc();if(c=='_'){if(x<size){c=cc();if(c=='d'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='e'){return endBlank(H.UTC_DATE);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}if(c=='t'){if(x<size){c=cc();if(c=='i'){if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='e'){if(x<size){c=cc();if(c=='s'){if(x<size){c=cc();if(c=='t'){if(x<size){c=cc();if(c=='a'){if(x<size){c=cc();if(c=='m'){if(x<size){c=cc();if(c=='p'){return endBlank(H.UTC_TIMESTAMP);}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}t=H.UTC_TIME;return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}endId(c);return x;}return x;}}